import { ProblemTemplate } from './types';

export const problemTemplates: ProblemTemplate[] = [
    // ===== ALGEBRA - Comparison =====
    {
        id: 'grade5-comparison-1',
        class: 5,
        subject: 'algebra',
        section: 'Числа и операции',
        topic: 'comparison',
        topic_title: 'Сравнение двузначных чисел',
        difficulty: 1,
        problemType: 'comparison',
        template: 'Сравните числа {a} и {b}. Выберите правильный знак.',
        parameters: {
            a: { type: 'int', min: 10, max: 99 },
            b: { type: 'int', min: 10, max: 99 },
        },
        answer_formula: 'a > b ? ">" : a < b ? "<" : "="',
        hint: 'Сравните числа поразрядно: десятки, затем единицы',
    },

    {
        id: 'grade5-comparison-2',
        class: 5,
        subject: 'algebra',
        section: 'Числа и операции',
        topic: 'comparison',
        topic_title: 'Сравнение трёхзначных чисел',
        difficulty: 1,
        problemType: 'comparison',
        template: 'Сравните числа {a} и {b}. Выберите правильный знак.',
        parameters: {
            a: { type: 'int', min: 100, max: 999 },
            b: { type: 'int', min: 100, max: 999 },
        },
        answer_formula: 'a > b ? ">" : a < b ? "<" : "="',
        hint: 'Сравните числа поразрядно: сотни, десятки, единицы',
    },

    // ===== ALGEBRA - Arithmetic =====
    {
        id: 'grade5-arithmetic-1',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        topic_title: 'Порядок действий: сложение и умножение',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: {a} + {b} × {c} = ?',
        parameters: {
            a: { type: 'int', min: 10, max: 50 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: 'a + b * c',
        hint: 'Сначала выполните умножение, затем сложение (порядок действий)',
    },

    {
        id: 'grade5-arithmetic-2',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        topic_title: 'Порядок действий: умножение и вычитание',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: {a} × {b} − {c} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 12 },
            b: { type: 'int', min: 2, max: 12 },
            c: { type: 'int', min: 1, max: 20 },
        },
        constraints: ['a * b - c > 0'],
        answer_formula: 'a * b - c',
        hint: 'Сначала выполните умножение, затем вычитание',
    },

    {
        id: 'grade5-arithmetic-3',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        topic_title: 'Порядок действий: скобки',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: ({a} + {b}) × {c} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 10 },
            b: { type: 'int', min: 2, max: 10 },
            c: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: '(a + b) * c',
        hint: 'Сначала выполните действие в скобках, затем умножение',
    },

    {
        id: 'grade5-arithmetic-4',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        topic_title: 'Два умножения',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Вычислите: {a} × {b} + {c} × {d} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 9 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
            d: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: 'a * b + c * d',
        hint: 'Сначала выполните оба умножения, затем сложите результаты',
    },

    {
        id: 'grade5-arithmetic-5',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        topic_title: 'Скобки и умножение',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Вычислите: ({a} − {b}) × {c} + {d} = ?',
        parameters: {
            a: { type: 'int', min: 10, max: 20 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 5 },
            d: { type: 'int', min: 5, max: 15 },
        },
        constraints: ['a > b'],
        answer_formula: '(a - b) * c + d',
        hint: 'Порядок действий: скобки, умножение, сложение',
    },

    // ===== LOGIC - Patterns/Sequences =====
    {
        id: 'grade5-patterns-1',
        class: 5,
        subject: 'logic',
        section: 'Закономерности',
        topic: 'patterns',
        topic_title: 'Арифметическая прогрессия',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Найдите следующее число в последовательности: {t1}, {t2}, {t3}, {t4}, ?',
        parameters: {
            a0: { type: 'int', min: 1, max: 10 },
            d: { type: 'int', min: 1, max: 5 },
            t1: { type: 'expression', value: 'a0' },
            t2: { type: 'expression', value: 'a0 + d' },
            t3: { type: 'expression', value: 'a0 + d * 2' },
            t4: { type: 'expression', value: 'a0 + d * 3' },
        },
        answer_formula: 'a0 + d * 4',
        hint: 'Найдите разность между соседними числами',
    },

    {
        id: 'grade5-patterns-2',
        class: 5,
        subject: 'logic',
        section: 'Закономерности',
        topic: 'patterns',
        topic_title: 'Геометрическая прогрессия',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Найдите следующее число в последовательности: {t1}, {t2}, {t3}, {t4}, ?',
        parameters: {
            a0: { type: 'int', min: 1, max: 5 },
            r: { type: 'int', min: 2, max: 3 },
            t1: { type: 'expression', value: 'a0' },
            t2: { type: 'expression', value: 'a0 * r' },
            t3: { type: 'expression', value: 'a0 * r * r' },
            t4: { type: 'expression', value: 'a0 * r * r * r' },
        },
        answer_formula: 'a0 * r * r * r * r',
        hint: 'Каждое следующее число получается умножением предыдущего на одно и то же число',
    },

    {
        id: 'grade5-patterns-3',
        class: 5,
        subject: 'logic',
        section: 'Закономерности',
        topic: 'patterns',
        topic_title: 'Пропущенный элемент',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Найдите пропущенное число: {t1}, {t2}, ?, {t4}, {t5}',
        parameters: {
            a0: { type: 'int', min: 2, max: 8 },
            d: { type: 'int', min: 2, max: 6 },
            t1: { type: 'expression', value: 'a0' },
            t2: { type: 'expression', value: 'a0 + d' },
            t4: { type: 'expression', value: 'a0 + d * 3' },
            t5: { type: 'expression', value: 'a0 + d * 4' },
        },
        answer_formula: 'a0 + d * 2',
        hint: 'Найдите разность между соседними числами',
    },

    // ===== ALGEBRA - Divisors =====
    {
        id: 'grade5-divisors-2',
        class: 5,
        subject: 'algebra',
        section: 'Делимость',
        topic: 'divisors',
        topic_title: 'Делимость на 2',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Число {n} делится на 2 без остатка?',
        parameters: {
            n: { type: 'int', min: 10, max: 99 },
        },
        answer_formula: 'n % 2 === 0 ? 1 : 0',
        hint: 'Число делится на 2, если его последняя цифра чётная (0, 2, 4, 6, 8). Ответьте 1 (да) или 0 (нет)',
    },

    // ===== ALGEBRA - Simple Equations =====
    {
        id: 'grade5-equations-1',
        class: 5,
        subject: 'algebra',
        section: 'Простые уравнения',
        topic: 'arithmetic',
        topic_title: 'Уравнение: x + a = b',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Решите уравнение: x + {a} = {b}',
        parameters: {
            a: { type: 'int', min: 5, max: 20 },
            b: { type: 'int', min: 15, max: 50 },
        },
        constraints: ['b > a'],
        answer_formula: 'b - a',
        hint: 'Чтобы найти x, вычтите {a} из обеих частей уравнения',
    },

    {
        id: 'grade5-equations-2',
        class: 5,
        subject: 'algebra',
        section: 'Простые уравнения',
        topic: 'arithmetic',
        topic_title: 'Уравнение: a × x = b',
        parameters: {
            a: { type: 'int', min: 2, max: 9 },
            x: { type: 'int', min: 2, max: 12 },
            b: { type: 'expression', value: 'a * x' },
        },
        answer_formula: 'x',
        hint: 'Чтобы найти x, разделите {b} на {a}',
    },

    {
        id: 'grade5-equations-3',
        class: 5,
        subject: 'algebra',
        section: 'Простые уравнения',
        topic: 'arithmetic',
        topic_title: 'Уравнение: x − a = b',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Решите уравнение: x − {a} = {b}',
        parameters: {
            a: { type: 'int', min: 5, max: 15 },
            b: { type: 'int', min: 10, max: 30 },
        },
        answer_formula: 'a + b',
        hint: 'Чтобы найти x, прибавьте {a} к обеим частям уравнения',
    },

    // ===== GEOMETRY - Perimeter =====
    {
        id: 'grade5-perimeter-1',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        topic_title: 'Периметр прямоугольника',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Прямоугольник имеет длину {a} см и ширину {b} см. Чему равен его периметр?',
        parameters: {
            a: { type: 'int', min: 3, max: 20 },
            b: { type: 'int', min: 3, max: 20 },
        },
        constraints: ['a !== b'],
        answer_formula: '2 * (a + b)',
        hint: 'Периметр = 2 × (длина + ширина)',
        common_mistakes: [
            { pattern: 'a + b', feedback: 'Ты сложил стороны только один раз. Периметр = 2 × (a + b).' },
            { pattern: 'a * b', feedback: 'Это формула площади, а не периметра.' },
        ],
    },

    {
        id: 'grade5-perimeter-2',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        topic_title: 'Периметр квадрата',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Квадрат имеет сторону {a} см. Чему равен его периметр?',
        parameters: {
            a: { type: 'int', min: 3, max: 15 },
        },
        answer_formula: '4 * a',
        hint: 'Периметр квадрата = 4 × сторона',
        common_mistakes: [
            { pattern: 'a', feedback: 'Это длина одной стороны. Периметр квадрата = 4 × сторона.' },
            { pattern: 'a * a', feedback: 'Это формула площади квадрата, а не периметра.' },
            { pattern: '2 * a', feedback: 'Ты умножил на 2, но у квадрата 4 стороны.' },
        ],
    },

    // ===== GEOMETRY - Area =====
    {
        id: 'grade5-area-1',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        topic_title: 'Площадь прямоугольника',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Прямоугольник имеет длину {a} см и ширину {b} см. Чему равна его площадь?',
        parameters: {
            a: { type: 'int', min: 3, max: 15 },
            b: { type: 'int', min: 3, max: 15 },
        },
        constraints: ['a !== b'],
        answer_formula: 'a * b',
        hint: 'Площадь = длина × ширина',
        common_mistakes: [
            { pattern: '2 * (a + b)', feedback: 'Это формула периметра, а не площади. Площадь = длина × ширина.' },
            { pattern: 'a + b', feedback: 'Площадь считается умножением, а не сложением.' },
        ],
    },

    {
        id: 'grade5-area-2',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        topic_title: 'Площадь квадрата',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Квадрат имеет сторону {a} см. Чему равна его площадь?',
        parameters: {
            a: { type: 'int', min: 3, max: 12 },
        },
        answer_formula: 'a * a',
        hint: 'Площадь квадрата = сторона × сторона',
        common_mistakes: [
            { pattern: '4 * a', feedback: 'Это формула периметра квадрата. Площадь = сторона × сторона.' },
            { pattern: 'a', feedback: 'Это длина стороны. Площадь квадрата = сторона².' },
        ],
    },

    {
        id: 'grade5-area-3',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        topic_title: 'Сторона квадрата по площади',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Квадрат имеет площадь {s} см². Чему равна его сторона?',
        parameters: {
            a: { type: 'int', min: 2, max: 10 },
            s: { type: 'expression', value: 'a * a' },
        },
        answer_formula: 'a',
        hint: 'Сторона квадрата = √площадь',
    },

    {
        id: 'grade5-area-4',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        topic_title: 'Ширина прямоугольника по площади',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Прямоугольник имеет площадь {s} см² и длину {a} см. Чему равна его ширина?',
        parameters: {
            a: { type: 'int', min: 3, max: 12 },
            b: { type: 'int', min: 2, max: 10 },
            s: { type: 'expression', value: 'a * b' },
        },
        constraints: ['a !== b'],
        answer_formula: 'b',
        hint: 'Ширина = площадь ÷ длина',
    },

    // ===== GEOMETRY - Triangle Types =====
    {
        id: 'grade5-triangle-1',
        class: 5,
        subject: 'geometry',
        section: 'Треугольники',
        topic: 'triangles',
        topic_title: 'Тип треугольника',
        difficulty: 2,
        problemType: 'text',
        template: 'Треугольник имеет стороны {a} см, {b} см и {c} см. Какой это треугольник? (равносторонний, равнобедренный или разносторонний)',
        parameters: {
            type: { type: 'choice', values: ['equilateral', 'isosceles', 'scalene'] },
            a: { type: 'int', min: 3, max: 10 },
            b: { type: 'expression', value: 'type === "equilateral" ? a : type === "isosceles" ? a : a + 1' },
            c: { type: 'expression', value: 'type === "equilateral" ? a : type === "isosceles" ? a + 2 : a + 2' },
        },
        answer_formula: 'type === "equilateral" ? "равносторонний" : type === "isosceles" ? "равнобедренный" : "разносторонний"',
        hint: 'Равносторонний: все стороны равны. Равнобедренный: две стороны равны. Разносторонний: все стороны разные',
    },

    {
        id: 'grade5-triangle-2',
        class: 5,
        subject: 'geometry',
        section: 'Треугольники',
        topic: 'triangles',
        topic_title: 'Неравенство треугольника',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Можно ли построить треугольник со сторонами {a} см, {b} см и {c} см? Ответьте 1 (да) или 0 (нет)',
        parameters: {
            a: { type: 'int', min: 2, max: 10 },
            b: { type: 'int', min: 2, max: 10 },
            c: { type: 'int', min: 2, max: 10 },
        },
        answer_formula: '(a + b > c && a + c > b && b + c > a) ? 1 : 0',
        hint: 'Неравенство треугольника: сумма любых двух сторон должна быть больше третьей',
    },

    {
        id: 'grade5-triangle-3',
        class: 5,
        subject: 'geometry',
        section: 'Треугольники',
        topic: 'triangles',
        topic_title: 'Третий угол треугольника',
        difficulty: 1,
        problemType: 'numeric',
        template: 'В треугольнике два угла равны {a}° и {b}°. Чему равен третий угол?',
        parameters: {
            a: { type: 'int', min: 30, max: 70 },
            b: { type: 'int', min: 30, max: 70 },
        },
        constraints: ['a + b < 180'],
        answer_formula: '180 - a - b',
        hint: 'Сумма углов в треугольнике равна 180°',
        common_mistakes: [
            { pattern: 'a + b', feedback: 'Сумма углов треугольника равна 180°. Третий угол = 180 − a − b.' },
            { pattern: '90 - a - b', feedback: 'Сумма углов треугольника равна 180°, а не 90°.' },
        ],
    },

    // ===== LOGIC - Magic Squares =====
    {
        id: 'grade5-magic-1',
        class: 5,
        subject: 'logic',
        section: 'Логические задачи',
        topic: 'magicSquare',
        topic_title: 'Магический квадрат: строка',
        difficulty: 3,
        problemType: 'numeric',
        template: 'В магическом квадрате сумма чисел в каждой строке, столбце и диагонали равна {sum}. Найдите пропущенное число: [{a}, {b}, ?]',
        parameters: {
            sum: { type: 'int', min: 15, max: 30 },
            a: { type: 'int', min: 1, max: 10 },
            b: { type: 'int', min: 1, max: 10 },
        },
        constraints: ['sum > a + b'],
        answer_formula: 'sum - a - b',
        hint: 'Сумма всех трёх чисел должна равняться магической константе',
    },

    {
        id: 'grade5-magic-2',
        class: 5,
        subject: 'logic',
        section: 'Логические задачи',
        topic: 'magicSquare',
        topic_title: 'Магический квадрат: найди x',
        difficulty: 3,
        problemType: 'numeric',
        template: 'В магическом квадрате сумма равна {sum}. Найдите x: [{a}, x, {c}]',
        parameters: {
            sum: { type: 'int', min: 18, max: 36 },
            a: { type: 'int', min: 3, max: 12 },
            c: { type: 'int', min: 3, max: 12 },
        },
        constraints: ['sum > a + c', 'a !== c'],
        answer_formula: 'sum - a - c',
        hint: 'x = сумма − первое число − третье число',
    },
];
