import { ProblemTemplate } from './types';

export const problemTemplates: ProblemTemplate[] = [
    // ===== ALGEBRA - Comparison =====
    {
        id: 'grade5-comparison-1',
        class: 5,
        subject: 'algebra',
        section: 'Числа и операции',
        topic: 'comparison',
        difficulty: 1,
        problemType: 'comparison',
        template: 'Сравните числа {a} и {b}. Выберите правильный знак.',
        parameters: {
            a: { type: 'int', min: 10, max: 99 },
            b: { type: 'int', min: 10, max: 99 },
        },
        answer_formula: 'a > b ? ">" : a < b ? "<" : "="',
        hint: 'Сравните числа поразрядно: десятки, затем единицы',
    },
    {
        id: 'grade5-comparison-2',
        class: 5,
        subject: 'algebra',
        section: 'Числа и операции',
        topic: 'comparison',
        difficulty: 1,
        problemType: 'comparison',
        template: 'Сравните числа {a} и {b}. Выберите правильный знак.',
        parameters: {
            a: { type: 'int', min: 100, max: 999 },
            b: { type: 'int', min: 100, max: 999 },
        },
        answer_formula: 'a > b ? ">" : a < b ? "<" : "="',
        hint: 'Сравните числа поразрядно: сотни, десятки, единицы',
    },
    {
        id: 'grade5-comparison-3',
        class: 5,
        subject: 'algebra',
        section: 'Числа и операции',
        topic: 'comparison',
        difficulty: 2,
        problemType: 'comparison',
        template: 'Сравните выражения: {a} × {b} и {c} × {d}. Выберите знак.',
        parameters: {
            a: { type: 'int', min: 2, max: 9 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
            d: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: 'a*b > c*d ? ">" : a*b < c*d ? "<" : "="',
        hint: 'Вычислите оба произведения, затем сравните',
    },

    // ===== ALGEBRA - Arithmetic =====
    {
        id: 'grade5-arithmetic-1',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: {a} + {b} × {c} = ?',
        parameters: {
            a: { type: 'int', min: 10, max: 50 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: 'a + b * c',
        hint: 'Сначала выполните умножение, затем сложение',
    },
    {
        id: 'grade5-arithmetic-2',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: {a} × {b} − {c} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 12 },
            b: { type: 'int', min: 2, max: 12 },
            c: { type: 'int', min: 1, max: 20 },
        },
        constraints: ['a * b - c > 0'],
        answer_formula: 'a * b - c',
        hint: 'Сначала выполните умножение, затем вычитание',
    },
    {
        id: 'grade5-arithmetic-3',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Вычислите: ({a} + {b}) × {c} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 10 },
            b: { type: 'int', min: 2, max: 10 },
            c: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: '(a + b) * c',
        hint: 'Сначала выполните действие в скобках, затем умножение',
    },
    {
        id: 'grade5-arithmetic-4',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Вычислите: {a} × ({b} − {c}) = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 9 },
            b: { type: 'int', min: 5, max: 20 },
            c: { type: 'int', min: 2, max: 9 },
        },
        constraints: ['b - c > 0'],
        answer_formula: 'a * (b - c)',
        hint: 'Сначала вычислите разность в скобках, затем умножьте',
    },
    {
        id: 'grade5-arithmetic-5',
        class: 5,
        subject: 'algebra',
        section: 'Арифметические операции',
        topic: 'arithmetic',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Вычислите: {a} × {b} + {c} × {d} = ?',
        parameters: {
            a: { type: 'int', min: 2, max: 9 },
            b: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
            d: { type: 'int', min: 2, max: 9 },
        },
        answer_formula: 'a * b + c * d',
        hint: 'Сначала выполните оба умножения, затем сложите результаты',
    },

    // ===== ALGEBRA - Patterns =====
    {
        id: 'grade5-patterns-1',
        class: 5,
        subject: 'algebra',
        section: 'Закономерности',
        topic: 'patterns',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Найдите следующее число: {a}, {b}, {c}, {d}, ?',
        parameters: {
            start: { type: 'int', min: 2, max: 10 },
            step: { type: 'int', min: 2, max: 8 },
            a: { type: 'expression', value: 'start' },
            b: { type: 'expression', value: 'start + step' },
            c: { type: 'expression', value: 'start + step * 2' },
            d: { type: 'expression', value: 'start + step * 3' },
        },
        answer_formula: 'start + step * 4',
        hint: 'Найдите разность между соседними числами',
    },
    {
        id: 'grade5-patterns-2',
        class: 5,
        subject: 'algebra',
        section: 'Закономерности',
        topic: 'patterns',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Найдите следующее число (геометрическая прогрессия): {a}, {b}, {c}, {d}, ?',
        parameters: {
            start: { type: 'int', min: 2, max: 4 },
            mult: { type: 'int', min: 2, max: 3 },
            a: { type: 'expression', value: 'start' },
            b: { type: 'expression', value: 'start * mult' },
            c: { type: 'expression', value: 'start * mult * mult' },
            d: { type: 'expression', value: 'start * mult * mult * mult' },
        },
        answer_formula: 'start * mult * mult * mult * mult',
        hint: 'Каждое число умножается на одно и то же число',
    },
    {
        id: 'grade5-patterns-3',
        class: 5,
        subject: 'algebra',
        section: 'Закономерности',
        topic: 'patterns',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Найдите пропущенное число: {a}, {b}, ?, {d}, {e}',
        parameters: {
            start: { type: 'int', min: 1, max: 10 },
            step: { type: 'int', min: 3, max: 8 },
            a: { type: 'expression', value: 'start' },
            b: { type: 'expression', value: 'start + step' },
            d: { type: 'expression', value: 'start + step * 3' },
            e: { type: 'expression', value: 'start + step * 4' },
        },
        answer_formula: 'start + step * 2',
        hint: 'Найдите разность между соседними числами и восстановите пропущенное',
    },

    // ===== ALGEBRA - Divisors =====
    {
        id: 'grade5-divisors-1',
        class: 5,
        subject: 'algebra',
        section: 'Делимость',
        topic: 'divisors',
        difficulty: 2,
        problemType: 'numeric',
        template: 'Найдите наименьшее общее кратное (НОК) чисел {a} и {b}',
        parameters: {
            a: { type: 'int', min: 2, max: 12 },
            b: { type: 'int', min: 2, max: 12 },
        },
        answer_formula: '(a * b) / (function gcd(x,y){return y===0?x:gcd(y,x%y)})(a,b)',
        hint: 'НОК(a, b) = (a × b) / НОД(a, b)',
    },
    {
        id: 'grade5-divisors-2',
        class: 5,
        subject: 'algebra',
        section: 'Делимость',
        topic: 'divisors',
        difficulty: 1,
        problemType: 'numeric',
        // Избегаем expression-зависимостей: задаём g,m,n напрямую и показываем a=g*m, b=g*n в тексте
        template: 'Найдите наибольший общий делитель (НОД) чисел {a} и {b}',
        parameters: {
            a: { type: 'choice', values: [6, 8, 10, 12, 14, 15, 18, 20, 24, 30] },
            b: { type: 'choice', values: [4, 6, 9, 10, 12, 15, 16, 18, 20, 24] },
        },
        answer_formula: '(function gcd(x,y){return y===0?x:gcd(y,x%y)})(a,b)',
        hint: 'НОД — наибольшее число, на которое оба числа делятся без остатка',
    },
    {
        id: 'grade5-divisors-3',
        class: 5,
        subject: 'algebra',
        section: 'Делимость',
        topic: 'divisors',
        difficulty: 1,
        problemType: 'numeric',
        template: 'На сколько равных групп можно разделить {a} яблок и {b} груш? (найдите НОД)',
        parameters: {
            a: { type: 'choice', values: [6, 8, 12, 16, 18, 20, 24] },
            b: { type: 'choice', values: [4, 6, 9, 12, 15, 18, 24] },
        },
        answer_formula: '(function gcd(x,y){return y===0?x:gcd(y,x%y)})(a,b)',
        hint: 'Найдите НОД(a, b)',
    },

    // ===== GEOMETRY - Perimeter =====
    {
        id: 'grade5-perimeter-1',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Прямоугольник имеет длину {a} см и ширину {b} см. Чему равен его периметр?',
        parameters: {
            a: { type: 'int', min: 3, max: 20 },
            b: { type: 'int', min: 3, max: 20 },
        },
        answer_formula: '2 * (a + b)',
        hint: 'Периметр = 2 × (длина + ширина)',
    },
    {
        id: 'grade5-perimeter-2',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Квадрат имеет сторону {a} см. Чему равен его периметр?',
        parameters: {
            a: { type: 'int', min: 3, max: 15 },
        },
        answer_formula: '4 * a',
        hint: 'Периметр квадрата = 4 × сторона',
    },
    {
        id: 'grade5-perimeter-3',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        difficulty: 2,
        problemType: 'numeric',
        // p = 4*side, избегаем expression: p задаётся через choice кратных 4
        template: 'Найдите сторону квадрата, если его периметр равен {p} см.',
        parameters: {
            p: { type: 'choice', values: [12, 16, 20, 24, 28, 32, 36, 40, 44, 48] },
        },
        answer_formula: 'p / 4',
        hint: 'Периметр квадрата = 4 × сторона, значит сторона = периметр ÷ 4',
    },
    {
        id: 'grade5-perimeter-4',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'perimeter',
        difficulty: 2,
        problemType: 'numeric',
        // Избегаем expression: задаём a и b напрямую, p вычисляем в answer_formula
        template: 'Периметр прямоугольника равен {p} см, одна сторона равна {a} см. Найдите другую сторону.',
        parameters: {
            a: { type: 'choice', values: [3, 4, 5, 6, 7, 8, 9, 10] },
            b: { type: 'choice', values: [3, 4, 5, 6, 7, 8, 9, 10] },
            p: { type: 'expression', value: '2 * (a + b)' },
        },
        answer_formula: 'b',
        hint: 'Периметр = 2 × (a + b), значит b = периметр ÷ 2 − a',
    },

    // ===== GEOMETRY - Area =====
    {
        id: 'grade5-area-1',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Прямоугольник имеет длину {a} см и ширину {b} см. Чему равна его площадь?',
        parameters: {
            a: { type: 'int', min: 3, max: 15 },
            b: { type: 'int', min: 3, max: 15 },
        },
        answer_formula: 'a * b',
        hint: 'Площадь = длина × ширина',
    },
    {
        id: 'grade5-area-2',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        difficulty: 1,
        problemType: 'numeric',
        template: 'Квадрат имеет сторону {a} см. Чему равна его площадь?',
        parameters: {
            a: { type: 'int', min: 3, max: 12 },
        },
        answer_formula: 'a * a',
        hint: 'Площадь квадрата = сторона × сторона',
    },
    {
        id: 'grade5-area-3',
        class: 5,
        subject: 'geometry',
        section: 'Периметр и площадь',
        topic: 'area',
        difficulty: 2,
        problemType: 'numeric',
        // Используем choice для a и b чтобы s=a*b всегда было целым и корректным
        template: 'Площадь прямоугольника равна {s} см², одна сторона равна {a} см. Найдите другую сторону.',
        parameters: {
            a: { type: 'choice', values: [3, 4, 5, 6, 7, 8] },
            b: { type: 'choice', values: [3, 4, 5, 6, 7, 8] },
            s: { type: 'expression', value: 'a * b' },
        },
        answer_formula: 'b',
        hint: 'Площадь = длина × ширина, значит ширина = площадь ÷ длина',
    },

    // ===== GEOMETRY - Triangle Types =====
    {
        id: 'grade5-triangle-1',
        class: 5,
        subject: 'geometry',
        section: 'Треугольники',
        topic: 'triangles',
        difficulty: 1,
        problemType: 'text',
        // Используем фиксированные наборы сторон через choice
        template: 'Треугольник имеет стороны {a} см, {b} см и {c} см. Какой это треугольник? (равносторонний, равнобедренный или разносторонний)',
        parameters: {
            set: { type: 'choice', values: [0, 1, 2, 3, 4, 5] },
            a: { type: 'expression', value: '[5,5,5,6,7,8][set]' },
            b: { type: 'expression', value: '[5,5,7,6,9,10][set]' },
            c: { type: 'expression', value: '[5,8,9,6,11,13][set]' },
        },
        answer_formula: '[\"равносторонний\",\"равнобедренный\",\"разносторонний\",\"равносторонний\",\"разносторонний\",\"разносторонний\"][set]',
        hint: 'Равносторонний: все стороны равны. Равнобедренный: две стороны равны. Разносторонний: все стороны разные',
    },
    {
        id: 'grade5-triangle-2',
        class: 5,
        subject: 'geometry',
        section: 'Треугольники',
        topic: 'triangles',
        difficulty: 1,
        problemType: 'text',
        template: 'Треугольник имеет углы {a}°, {b}° и {c}°. Прямоугольный, остроугольный или тупоугольный?',
        parameters: {
            set: { type: 'choice', values: [0, 1, 2, 3, 4, 5] },
            a: { type: 'expression', value: '[90,60,120,45,30,110][set]' },
            b: { type: 'expression', value: '[45,70,30,90,60,40][set]' },
            c: { type: 'expression', value: '[45,50,30,45,90,30][set]' },
        },
        answer_formula: '[\"прямоугольным\",\"остроугольным\",\"тупоугольным\",\"прямоугольным\",\"прямоугольным\",\"тупоугольным\"][set]',
        hint: 'Прямоугольный: один угол 90°. Тупоугольный: один угол > 90°. Остроугольный: все углы < 90°',
    },

    // ===== LOGIC - Magic Squares =====
    {
        id: 'grade5-magic-1',
        class: 5,
        subject: 'logic',
        section: 'Логические задачи',
        topic: 'magicSquare',
        difficulty: 2,
        problemType: 'numeric',
        template: 'В магическом квадрате сумма чисел в каждой строке равна {sum}. Найдите пропущенное число: [{a}, {b}, ?]',
        parameters: {
            sum: { type: 'int', min: 12, max: 24 },
            a: { type: 'int', min: 1, max: 8 },
            b: { type: 'int', min: 1, max: 8 },
        },
        constraints: ['sum - a - b > 0', 'sum - a - b <= 15'],
        answer_formula: 'sum - a - b',
        hint: 'a + b + ? = сумма строки, значит ? = сумма − a − b',
    },
    {
        id: 'grade5-magic-2',
        class: 5,
        subject: 'logic',
        section: 'Логические задачи',
        topic: 'magicSquare',
        difficulty: 3,
        problemType: 'numeric',
        template: 'Магическая константа равна {sum}. В диагонали стоят числа {a}, ?, {c}. Найдите пропущенное.',
        parameters: {
            sum: { type: 'int', min: 15, max: 27 },
            a: { type: 'int', min: 2, max: 9 },
            c: { type: 'int', min: 2, max: 9 },
        },
        constraints: ['sum - a - c > 0', 'sum - a - c !== a', 'sum - a - c !== c'],
        answer_formula: 'sum - a - c',
        hint: 'a + ? + c = магическая константа, значит ? = константа − a − c',
    },
];
